import React from "react";
// import bg from "../assets/services/services.png";
import { Helmet } from "react-helmet";
import { styled } from "styled-components";

export const Policy = () => {
  return (
    <PolicyWrapper className="px-20 pb-28">
      <Helmet>
        <title>Privacy Policy</title>
      </Helmet>
      <div className="w-full h-60 flex justify-center items-center">
        {/* <img src="" className="h-60 w-full" /> */}
        <div className="text-5xl font-bold text-[#254c77] absolute">
          <h3>Privacy Policy</h3>
        </div>
      </div>
      <p className="px-5 py-3">Last updated: January 19, 2023</p>
      <div className="px-28 space-y-8 mt-10">
        <p>
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <p>
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy.
        </p>
        <h3 className="text-4xl font-bold">Interpretation and Definitions</h3>
      </div>
      <div className="px-28 mt-10 space-y-8">
        <h3 className="text-3xl font-bold">Interpretation</h3>
        <p>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>
        <h3 className="text-4xl font-bold">Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <div className="px-10 space-y-6">
          <ul style={{ listStyle: "initial" }} className="px-10 space-y-5">
            <li>
              Account means a unique account created for You to access our
              Service or parts of our Service.
            </li>
            <li>
              Company (referred to as either "the Company", "We", "Us" or "Our"
              in this Agreement) refers to Wire Wings PVT LTD, S Trade Centre,
              Near Police Headquarters, Sector – 7, Gomti Nagar Extensions,
              Lucknow
            </li>
            <li>
              Cookies are small files that are placed on Your computer, mobile
              device or any other device by a website, containing the details of
              Your browsing history on that website among its many uses.
            </li>
            <li>Country refers to: Uttar Pradesh, India</li>
            <li>
              Device means any device that can access the Service such as a
              computer, a cellphone or a digital tablet.
            </li>
            <li>
              Personal Data is any information that relates to an identified or
              identifiable individual.
            </li>
            <li>Service refers to the Website.</li>
            <li>Country refers to: Uttar Pradesh, India</li>
            <li>
              Service Provider means any natural or legal person who processes
              the data on behalf of the Company. It refers to third-party
              companies or individuals employed by the Company to facilitate the
              Service, to provide the Service on behalf of the Company, to
              perform services related to the Service or to assist the Company
              in analyzing how the Service is used.
            </li>
            <li>
              Usage Data refers to data collected automatically, either
              generated by the use of the Service or from the Service
              infrastructure itself (for example, the duration of a page visit).
            </li>
            <li>
              Website refers to Wire Wings, accessible from https://wirewings.in
            </li>
            <li>
              You means the individual accessing or using the Service, or the
              company, or other legal entity on behalf of which such individual
              is accessing or using the Service, as applicable.
            </li>
          </ul>
          <h3 className="text-4xl font-bold">
            Collecting and Using Your Personal Data
          </h3>
          <h3 className="text-3xl font-bold">Types of Data Collected</h3>
          <h3 className="text-2xl font-bold">Personal Data </h3>
          <p>
            While using Our Service, We may ask You to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You. Personally identifiable information may include, but
            is not limited to:
          </p>
          <div className="space-y-6">
            <ul style={{ listStyle: "initial" }} className="px-10 space-y-5">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Usage Data</li>
            </ul>
          </div>
          <h3 className="text-2xl font-bold">Usage Data</h3>
          <p>Usage Data is collected automatically when using the Service</p>
          <p>
            Usage Data may include information such as Your Device's Internet
            Protocol address (e.g. IP address), browser type, browser version,
            the pages of our Service that You visit, the time and date of Your
            visit, the time spent on those pages, unique device identifiers and
            other diagnostic data.
          </p>
          <p>
            When You access the Service by or through a mobile device, We may
            collect certain information automatically, including, but not
            limited to, the type of mobile device You use, Your mobile device
            unique ID, the IP address of Your mobile device, Your mobile
            operating system, the type of mobile Internet browser You use,
            unique device identifiers and other diagnostic data.
          </p>
          <p>
            We may also collect information that Your browser sends whenever You
            visit our Service or when You access the Service by or through a
            mobile device.
          </p>
          <h3 className="text-2xl font-bold">
            Tracking Technologies and Cookies
          </h3>
          <p>
            We use Cookies and similar tracking technologies to track the
            activity on Our Service and store certain information. Tracking
            technologies used are beacons, tags, and scripts to collect and
            track information and to improve and analyze Our Service. The
            technologies We use may include:
          </p>
          <h3 className="text-2xl font-bold">Personal Data </h3>
          <div className="space-y-6">
            <ul style={{ listStyle: "initial" }} className="px-10 space-y-5">
              <li>
                <b>Cookies or Browser Cookies.</b> A cookie is a small file
                placed on Your Device. You can instruct Your browser to refuse
                all Cookies or to indicate when a Cookie is being sent. However,
                if You do not accept Cookies, You may not be able to use some
                parts of our Service. Unless you have adjusted Your browser
                setting so that it will refuse Cookies, our Service may use
                Cookies.
              </li>
              <li>
                <b>Web Beacons.</b> Certain sections of our Service and our
                emails may contain small electronic files known as web beacons
                (also referred to as clear gifs, pixel tags, and single-pixel
                gifs) that permit the Company, for example, to count users who
                have visited those pages or opened an email and for other
                related website statistics (for example, recording the
                popularity of a certain section and verifying system and server
                integrity).
              </li>
              <li>
                Cookies can be "Persistent" or "Session" Cookies. Persistent
                Cookies remain on Your personal computer or mobile device when
                You go offline, while Session Cookies are deleted as soon as You
                close Your web browser.
              </li>
              <li>
                We use both Session and Persistent Cookies for the purposes set
                out below:
              </li>
            </ul>
          </div>
          <p></p>
          <p></p>
          <h3 className="text-2xl font-bold">Personal Data </h3>
          <div className="space-y-6">
            <ul style={{ listStyle: "initial" }} className="px-10 space-y-5">
              <li>Necessary / Essential Cookies</li>
              <li>Type: Session Cookies</li>
              <li>Administered by: Us</li>
            </ul>
          </div>
          <div className="space-y-6">
            <ul style={{ listStyle: "initial" }} className="px-10 space-y-5">
              <li>Type: Persistent Cookies</li>
              <li> Administered by: Us</li>
              <li>
                Purpose: These Cookies identify if users have accepted the use
                of cookies on the Website.
              </li>
            </ul>
          </div>
          <p>
            Purpose: These Cookies are essential to provide You with services
            available through the Website and to enable You to use some of its
            features. They help to authenticate users and prevent fraudulent use
            of user accounts. Without these Cookies, the services that You have
            asked for cannot be provided, and We only use these Cookies to
            provide You with those services.
          </p>
          <p>Cookies Policy / Notice Acceptance Cookies</p>
        </div>
      </div>
    </PolicyWrapper>
  );
};

const PolicyWrapper = styled.div``;
